name: gymguide_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  supabase_flutter: ^2.5.0
  video_player: ^2.8.6
  font_awesome_flutter: 10.7.0
  shared_preferences: ^2.5.3
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  image_picker: ^1.0.7
  purchases_flutter: ^9.16.0
  purchases_ui_flutter: ^9.16.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  mixpanel_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  # ------ ASSETS ------
  assets:

    - assets/svg/male/front/
    - assets/svg/male/back/
    - assets/svg/female/front/
    - assets/svg/female/back/
    - assets/svg/logo/
    - assets/svg/mealsicons/
    - assets/svg/socialmedia/
    - assets/banner/
    - assets/quizimg.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/svg/logo/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/svg/logo/icontransparent.png"
  web:
    generate: true
    image_path: "assets/svg/logo/icontransparent.png"
    background_color: "#ffffff"
    theme_color: "#d80000"
